# B"H

name: Resize

on:
  workflow_dispatch:
    inputs:
      size:
        description: 'Number of nodes'     
        required: true
        default: '0'
      pool_name:
        description: "pool name"
        required: true
        default: "default-pool"

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: us-central1-c   

jobs:
  setup-resize:
    name: Setup, Resize
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v0.2.1
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Resize the cluster
    - name: Resize
      run: |-
        gcloud container clusters resize ${{ secrets.GKE_CLUSTER_NAME }} \
        --node-pool=${{ github.event.inputs.pool_name }} \
        --num-nodes=${{ github.event.inputs.size }} \
        --zone ${{ env.GKE_ZONE }} \
        --quiet